{
  "template_name" : "First Year",
  "orientation": "landscape",

  "pages" : [
    {
      "template_path": "First Year Template Cover.png",
      "meta": "cover",
      "name": "First Year Template Cover",
      "elements": [
        {
          "x": 64,
          "y": 76,
          "w": 95,
          "h": 84,
          "radius": 0,
          "type": "image",
          "name": "cover",
        },
        {
          "x": 166,
          "y": 76,
          "w": 96,
          "h": 83,
          "radius": 0,
          "type": "image",
          "name": "cover",
        },
        {
          "x": 266,
          "y": 76,
          "w": 96,
          "h": 83,
          "radius": 0,
          "type": "image",
          "name": "cover",
        },
        {
          "x": 45,
          "y": 259,
          "w": 244,
          "h": 30,
          "radius": 0,
          "type": "text",
          "name": "cover",
          "font-name": "Baskerville-Italic",
          "font-color": "47,74,19",
          "font-size": 18
        }
      ]
    },
    {
      "template_path": "First Year Template P1.png",
      "meta": "page",
      "name": "First Year Template P1",
      "elements": [
        {
          "x": 45.5,
          "y": 33.5,
          "w": 120.50,
          "h": 85,
          "radius": 0,
          "type": "image",
          "name": "P1",
        },
        {
          "x": 140,
          "y": 98,
          "w": 91.5,
          "h": 123,
          "radius": 0,
          "type": "image",
          "name": "P1",
        },
        {
          "x": 28,
          "y": 181,
          "w": 124,
          "h": 90.5,
          "radius": 0,
          "type": "image",
          "name": "P1",
        },
        {
          "x": 203,
          "y": 212,
          "w": 124,
          "h": 90,
          "radius": 0,
          "type": "image",
          "name": "P1", 
        },
        {
          "x": 320,
          "y": 114,
          "w": 143,
          "h": 75,
          "radius": 0,
          "type": "text",
          "name": "P1",
          "font-name": "Baskerville-Italic",
          "font-color": "47,74,19",
          "font-size": 24,
        }
      ]
    },
    {
      "template_path": "First Year Template P2.png",
      "meta": "page",
      "name": "First Year Template P2",
      "elements": [
        {
          "x": 64,
          "y": 35,
          "w": 146,
          "h": 68,
          "radius": 0,
          "type": "text",
          "name": "P2",
          "font-name": "Gurmukhi MN",
          "font-color": "47,74,19",
          "font-size": 20,
        },
        {
          "x": 295,
          "y": 44,
          "w": 131,
          "h": 133,
          "radius": 8.5,
          "type": "image",
          "name": "P2",
        },
        {
          "x": 22,
          "y": 123,
          "w": 120,
          "h": 160,
          "radius": -7,
          "type": "image",
          "name": "P2",
        },
        {
          "x": 148,
          "y": 137,
          "w": 88,
          "h": 124,
          "radius": 0,
          "type": "image",
          "name": "P2", 
        },
        {
          "x": 323.58,
          "y": 211.04,
          "w": 102.74,
          "h": 42.64,
          "radius": 10.5,
          "type": "text",
          "name": "P2",
          "font-name": "Gurmukhi MN",
          "font-color": "47,74,19",
          "font-size": 16,
        }
      ]
    },
    {
      "template_path": "First Year Template P3.png",
      "meta": "page",
      "name": "First Year Template P3",
      "elements": [
        {
          "x": 95,
          "y": 27,
          "w": 71,
          "h": 74,
          "radius": 0,
          "type": "image",
          "name": "P3",
        },
        {
          "x": 296,
          "y": 26,
          "w": 85,
          "h": 80,
          "radius": 10,
          "type": "image",
          "name": "P3",
        },
        {
          "x": 306,
          "y": 122,
          "w": 58,
          "h": 62,
          "radius": 0,
          "type": "image",
          "name": "P3",
        },
        {
          "x": 299,
          "y": 204,
          "w": 87,
          "h": 82,
          "radius": -5.54,
          "type": "image",
          "name": "P3", 
        },
        {
          "x": 194,
          "y": 202,
          "w": 81,
          "h": 97,
          "radius": 0,
          "type": "image",
          "name": "P3",
        },
        {
          "x": 83,
          "y": 203,
          "w": 93,
          "h": 81,
          "radius": -10.53,
          "type": "image",
          "name": "P3",
        }
      ]
    },
    {
        "template_path": "First Year Template P4.png",
      "meta": "page",
      "name": "First Year Template P4",
      "elements": [
        {
          "x": 45,
          "y": 35,
          "w": 178,
          "h": 228,
          "radius": -3.2,
          "type": "image",
          "name": "P4",
        },
        {
          "x": 277,
          "y": 104,
          "w": 152,
          "h": 107,
          "radius": 0,
          "type": "text",
          "name": "P4",
          "font-name": "Gurmukhi MN",
          "font-color": "47,74,19",
          "font-size": 20,
        }
      ]
    },
    {
        "template_path": "First Year Template P5.png",
      "meta": "page",
      "name": "First Year Template P5",
      "elements": [
        {
          "x": 22,
          "y": 18,
          "w": 157,
          "h": 157,
          "radius": 0,
          "type": "image",
          "name": "P5",
        },
        {
          "x": 155,
          "y": 60,
          "w": 206.85,
          "h": 206.85,
          "radius": 0,
          "type": "image",
          "name": "P5",
        },
        {
          "x": 63.5,
          "y": 151.5,
          "w": 118,
          "h": 118,
          "radius": 0,
          "type": "image",
          "name": "P5",
        }
      ]
    },
    {
        "template_path": "First Year Template P6.png",
      "meta": "page",
      "name": "First Year Template P6",
      "elements": [
        {
          "x": 43,
          "y": 45,
          "w": 370,
          "h": 245,
          "radius": -4.5,
          "type": "image",
          "name": "P6",
        },
        {
          "x": 72,
          "y": 240,
          "w": 343,
          "h": 31,
          "radius": -4.5,
          "type": "text",
          "name": "P6",
          "font-name": "Gurmukhi MN",
          "font-color": "47,74,19",
          "font-size": 16,
        }
      ]
    },
    {
        "template_path": "First Year Template P7.png",
      "meta": "page",
      "name": "First Year Template P7",
      "elements": [
        {
          "x": 61,
          "y": 47,
          "w": 142,
          "h": 195,
          "radius": -5.8,
          "type": "image",
          "name": "P7",
        },
        {
          "x": 335,
          "y": 150,
          "w": 100,
          "h": 96,
          "radius": 0,
          "type": "image",
          "name": "P7",
        },
        {
          "x": 205,
          "y": 65,
          "w": 136,
          "h": 160,
          "radius": 13.5,
          "type": "image",
          "name": "P7",
        },
        {
          "x": 70,
          "y": 265,
          "w": 328,
          "h": 28,
          "radius": 0,
          "type": "text",
          "name": "P7",
          "font-name": "Gurmukhi MN",
          "font-color": "47,74,19",
          "font-size": 18,
        }
      ]
    }
  ]
}

